imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        enabled: true
        collect: true

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    logging: true
    disable_delivery: true

doctrine:
    dbal:
        default_connection: test
        connections:
            test:
                driver:   pdo_sqlite
                path:     %kernel.root_dir%/cache/test/test.sqlite
    orm:
        dql:
            string_functions:
                Soundex: Truckee\MatchBundle\DQL\Soundex
            datetime_functions:
                month: DoctrineExtensions\Query\Sqlite\Month
                year: DoctrineExtensions\Query\Sqlite\Year
                
liip_functional_test:
    cache_sqlite_db: true
