app:
    resource: "@TruckeeMatchBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
##add following for PUGX multi-user bundle

staff_registration:
    path:  /register/staff

volunteer_registration:
    path:  /register/volunteer

admin_registration:
    path:  /register/admin
