app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
##add following for PUGX multi-user bundle

staff_registration:
    path:  /register/staff
    defaults: { _controller: AppBundle:Registration:registerStaff }

volunteer_registration:
    path:  /register/volunteer
    defaults: { _controller: AppBundle:Registration:registerVolunteer }

admin_registration:
    path:  /register/admin
    defaults: { _controller: AppBundle:Registration:registerAdmin }
