# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_STAFF: ROLE_USER
        ROLE_ADMIN: ROLE_STAFF
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            access_denied_url: /login
            form_login:
                provider: fos_userbundle
                failure_path:    /login
                failure_forward: true
                default_target_path: /
                always_use_default_target_path: true
            logout:       true
            anonymous:    ~
            
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }  
