# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    form.type.focus:
        class: AppBundle\Form\Field\FocusFieldType
        tags:
            - { name: form.type, alias: focuses }
        arguments: ["@app.focus_repository"]
            
    form.type.skill:
        class: AppBundle\Form\Field\SkillFieldType
        tags:
            - { name: form.type, alias: skills }
        arguments:  ["@app.skill_repository"]
            
    app.focus_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: 
            - AppBundle\Entity\Focus
            
    app.skill_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Skill
            
    app.tools.user_manipulator:
        class:      AppBundle\Tools\UserManipulator
        arguments:  [@fos_user.user_manager, @pugx_user.manager.user_discriminator]

    fos_user.mailer.twig_swift:
       class: FOS\UserBundle\Mailer\TwigSwiftMailer
       arguments:
            - @mailer
            - @router
            - @twig
            - { template: { confirmation: %fos_user.registration.confirmation.template%, resetting: %fos_user.resetting.email.template% }, from_email: { confirmation: %fos_user.registration.confirmation.from_email%, resetting: %fos_user.resetting.email.from_email% } }

    admin.mailer:
        class: AppBundle\Tools\AdminMailer
        arguments:
            - '@mailer'
#            - '@router'
            - '@twig'
            - %admin_email%
            - '@doctrine.orm.entity_manager'

    app.toolbox:
        class: AppBundle\Tools\Toolbox
        arguments: [@doctrine.orm.entity_manager]
            
    app.registration_listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments: 
            em: @doctrine.orm.entity_manager
            messager: @admin.mailer
            tools: @app.toolbox
        tags:
            - { name: kernel.event_subscriber }
