# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: Truckee\MatchBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    form.type.focus:
        class: Truckee\MatchBundle\Form\Field\FocusFieldType
        tags:
            - { name: form.type, alias: focuses }
        arguments: ["@truckee_match.focus_repository"]
            
    form.type.skill:
        class: Truckee\MatchBundle\Form\Field\SkillFieldType
        tags:
            - { name: form.type, alias: skills }
        arguments:  ["@truckee_match.skill_repository"]
            
    truckee_match.focus_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: 
            - Truckee\MatchBundle\Entity\Focus
            
    truckee_match.skill_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Truckee\MatchBundle\Entity\Skill
            
    truckee_match.tools.user_manipulator:
        class:      Truckee\MatchBundle\Tools\UserManipulator
        arguments:  [@fos_user.user_manager, @pugx_user.manager.user_discriminator]

    fos_user.mailer.twig_swift:
       class: FOS\UserBundle\Mailer\TwigSwiftMailer
       arguments:
            - @mailer
            - @router
            - @twig
            - { template: { confirmation: %fos_user.registration.confirmation.template%, resetting: %fos_user.resetting.email.template% }, from_email: { confirmation: %fos_user.registration.confirmation.from_email%, resetting: %fos_user.resetting.email.from_email% } }

    admin.mailer:
        class: Truckee\MatchBundle\Tools\AdminMailer
        arguments:
            - '@mailer'
            - '@twig'
            - %admin_email%
            - '@doctrine.orm.entity_manager'
            - '@truckee_match.toolbox'

    truckee_match.toolbox:
        class: Truckee\MatchBundle\Tools\Toolbox
        arguments: [@doctrine.orm.entity_manager]
            
    truckee_match.registration_listener:
        class: Truckee\MatchBundle\EventListener\RegistrationListener
        arguments: 
            em: @doctrine.orm.entity_manager
            messager: @admin.mailer
        tags:
            - { name: kernel.event_subscriber }

    truckee_match.twig_extension.user_type:
        class:      Truckee\MatchBundle\Tools\UserTypeExtension
        arguments:  [@security.token_storage, @truckee_match.toolbox]
        tags:
            - { name: twig.extension}
